title: My Cybersecurity Blog
description: Documenting my progress in cybersecurity
author: ADSEC117
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-feed
timezone: 'America/New_York'
